/*
 GROUP HEADERS GENERATED BY: https://patorjk.com/software/taag/#p=display&h=0&v=1&c=c&f=ANSI%20Shadow&t=STAGE%20FUNCS

 SUB GROUP HEADERS GENERATED BY: https://patorjk.com/software/taag/#p=display&h=1&v=1&c=c&f=Banner3&t=permissions

 */

set search_path = public, const, ext, stage, helpers, internal, unsecure, auth, triggers;

select *
from start_version_update('1.6', 'Journal level control helper', _component := 'common_helpers',
                          _description := 'Function to check journal logging level from sys_param');

/*
 * Journal Level Control
 * =====================
 *
 * Checks the journal logging level from const.sys_param and determines
 * whether a journal entry should be created based on the event type.
 *
 * Levels:
 * - 'all'    : Log everything including read operations
 * - 'update' : Log only state-changing operations (default)
 * - 'none'   : Disable journaling entirely
 *
 * Usage:
 *   if helpers.should_log_journal() then
 *       perform create_journal_message(...);
 *   end if;
 *
 *   -- For read-only operations:
 *   if helpers.should_log_journal(true) then
 *       perform create_journal_message(...);
 *   end if;
 */
create or replace function helpers.should_log_journal(_is_read_only boolean default false)
    returns boolean
    stable
    language sql
as
$$
select case (select text_value from const.sys_param
             where group_code = 'journal' and code = 'level')
    when 'none' then false
    when 'update' then not _is_read_only
    else true  -- 'all' or not set defaults to logging everything
end;
$$;

/*
 * Check if event is read-only by event_id
 *
 * Looks up the is_read_only flag from const.event_code.
 * Used by create_journal_message to automatically determine if logging should happen.
 */
create or replace function helpers.is_event_read_only(_event_id integer)
    returns boolean
    stable
    language sql
as
$$
select coalesce(
    (select is_read_only from const.event_code where event_id = _event_id),
    false
);
$$;

select *
from stop_version_update('1.6', _component := 'common_helpers');
