/*
 GROUP HEADERS GENERATED BY: https://patorjk.com/software/taag/#p=display&h=0&v=1&c=c&f=ANSI%20Shadow&t=STAGE%20FUNCS

 SUB GROUP HEADERS GENERATED BY: https://patorjk.com/software/taag/#p=display&h=1&v=1&c=c&f=Banner3&t=permissions

 */

set search_path = public, const, ext, stage, helpers, internal, unsecure, auth, triggers;

select *
from start_version_update('1.7', 'Helper fixes: delete_jsonb_fields, normalize_text trim, get_code regex, random_string length',
                          _component := 'common_helpers',
                          _description := 'delete_jsonb_fields: drop STRICT so a null field-list returns the data unchanged instead of null (the in-body branch was dead code under STRICT), and remove a leftover debug RAISE INFO. normalize_text: add a _trim mode parameter (left / right / both, default both; none disables). get_code: fix the character class [^a-z0-9\\-_] which formed an unintended range and let backslash/]/^ pass through. random_string: support lengths beyond md5''s 32 characters.');


/***
 *    ███╗   ██╗ ██████╗ ██████╗ ███╗   ███╗ █████╗ ██╗     ██╗███████╗███████╗    ████████╗███████╗██╗  ██╗████████╗
 *    ████╗  ██║██╔═══██╗██╔══██╗████╗ ████║██╔══██╗██║     ██║╚══███╔╝██╔════╝    ╚══██╔══╝██╔════╝╚██╗██╔╝╚══██╔══╝
 *    ██╔██╗ ██║██║   ██║██████╔╝██╔████╔██║███████║██║     ██║  ███╔╝ █████╗         ██║   █████╗   ╚███╔╝    ██║
 *    ██║╚██╗██║██║   ██║██╔══██╗██║╚██╔╝██║██╔══██║██║     ██║ ███╔╝  ██╔══╝         ██║   ██╔══╝   ██╔██╗    ██║
 *    ██║ ╚████║╚██████╔╝██║  ██║██║ ╚═╝ ██║██║  ██║███████╗██║███████╗███████╗       ██║   ███████╗██╔╝ ██╗   ██║
 *    ╚═╝  ╚═══╝ ╚═════╝ ╚═╝  ╚═╝╚═╝     ╚═╝╚═╝  ╚═╝╚══════╝╚═╝╚══════╝╚══════╝       ╚═╝   ╚══════╝╚═╝  ╚═╝   ╚═╝
 *
 */

-- v1-2 declared this function STRICT, which makes PostgreSQL return null whenever ANY
-- argument is null -- before the body runs. That defeated the `_fields_to_delete is null
-- then return _data` branch (dead code) and, because _fields_to_delete defaults to null,
-- turned the single-argument call delete_jsonb_fields(data) into a silent data-nuking null.
-- Removing STRICT lets the existing body handle nulls as intended:
--   delete_jsonb_fields(data)            -> data unchanged (no-op)
--   delete_jsonb_fields(data, null)      -> data unchanged (no-op)
--   delete_jsonb_fields(null, fields)    -> null
create or replace function helpers.delete_jsonb_fields(_data jsonb, _fields_to_delete text[] default null)
    returns jsonb
    immutable
    parallel safe
    cost 0.05
    language plpgsql
as
$$
declare
    field    text;
    __result jsonb;
begin

    if _data is null then
        return null;
    elseif _fields_to_delete is null then
        return _data;
    end if;

    __result := _data;

    foreach field in array _fields_to_delete
        loop
            __result := __result - field;
        end loop;

    return __result;
end;
$$;


/***
 *    ████████╗██████╗ ██╗███╗   ███╗
 *    ╚══██╔══╝██╔══██╗██║████╗ ████║
 *       ██║   ██████╔╝██║██╔████╔██║
 *       ██║   ██╔══██╗██║██║╚██╔╝██║
 *       ██║   ██║  ██║██║██║ ╚═╝ ██║
 *       ╚═╝   ╚═╝  ╚═╝╚═╝╚═╝     ╚═╝
 *
 */

-- The prior overloads are dropped first: adding a defaulted _trim parameter would otherwise
-- leave the shorter signature matching a defaulted call, which PostgreSQL rejects as an
-- ambiguous function reference. Both the 2-arg and any earlier 3-arg form are removed so this
-- migration is safe to apply regardless of the previously deployed shape.
drop function if exists helpers.normalize_text(text, boolean);
drop function if exists helpers.normalize_text(text, boolean, boolean);

-- _trim selects the whitespace-trimming mode: 'both' (default), 'left', 'right', or 'none'
-- (any other value is treated as no trimming).
create function helpers.normalize_text(_text text, _lower_text boolean default true, _trim text default 'both')
    returns text
    immutable
    strict
    parallel safe
    cost 1
    language sql
as
$$
with normalized as (select case when _lower_text then lower(ext.unaccent(_text)) else ext.unaccent(_text) end as value)
select case lower(_trim)
           when 'both' then btrim(value)
           when 'left' then ltrim(value)
           when 'right' then rtrim(value)
           else value
       end
from normalized;
$$;


/***
 *     ██████╗ ███████╗████████╗     ██████╗ ██████╗ ██████╗ ███████╗
 *    ██╔════╝ ██╔════╝╚══██╔══╝    ██╔════╝██╔═══██╗██╔══██╗██╔════╝
 *    ██║  ███╗█████╗     ██║       ██║     ██║   ██║██║  ██║█████╗
 *    ██║   ██║██╔══╝     ██║       ██║     ██║   ██║██║  ██║██╔══╝
 *    ╚██████╔╝███████╗   ██║       ╚██████╗╚██████╔╝██████╔╝███████╗
 *     ╚═════╝ ╚══════╝   ╚═╝        ╚═════╝ ╚═════╝ ╚═════╝ ╚══════╝
 *
 */

-- The original character class [^a-z0-9\-_] was written with a doubled backslash, so the
-- fragment \-_ was parsed as the range 0x5C..0x5F -- letting backslash, ']' and '^' pass
-- through unreplaced instead of being collapsed to the separator. The fix normalises every
-- run of non-alphanumeric characters to a single separator (matching the long-standing
-- behaviour where runs of spaces/punctuation collapse); the 'i' flag is dropped as redundant
-- because the text is already lower-cased.
create or replace function helpers.get_code(_text text, _separator text default '_')
    returns text
    immutable
    parallel safe
    cost 1
    language sql
as
$$
    -- removes accents (diacritic signs) from a given string --
with _unaccented as (select ext.unaccent(_text) as _title),
     -- lowercases the string
     _lowercase as (select lower(_title) as _title
                    from _unaccented),
     -- replaces every run of characters that is not a lowercase letter or number with the separator
     _hyphenated as (select regexp_replace(_title, '[^a-z0-9]+', _separator, 'g') as _title
                     from _lowercase),
     -- trims the separator if it exists on the head or tail of the string
     _trimmed as (select trim(BOTH _separator FROM _title) as _title
                  from _hyphenated)
select _title
from _trimmed;
$$;


/***
 *    ██████╗  █████╗ ███╗   ██╗██████╗  ██████╗ ███╗   ███╗    ███████╗████████╗██████╗
 *    ██╔══██╗██╔══██╗████╗  ██║██╔══██╗██╔═══██╗████╗ ████║    ██╔════╝╚══██╔══╝██╔══██╗
 *    ██████╔╝███████║██╔██╗ ██║██║  ██║██║   ██║██╔████╔██║    ███████╗   ██║   ██████╔╝
 *    ██╔══██╗██╔══██║██║╚██╗██║██║  ██║██║   ██║██║╚██╔╝██║    ╚════██║   ██║   ██╔══██╗
 *    ██║  ██║██║  ██║██║ ╚████║██████╔╝╚██████╔╝██║ ╚═╝ ██║    ███████║   ██║   ██║  ██║
 *    ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝  ╚═════╝ ╚═╝     ╚═╝    ╚══════╝   ╚═╝   ╚═╝  ╚═╝
 *
 */

-- md5() only yields 32 hex characters, so the previous substring(md5(...), 0, len + 1) silently
-- capped the result at 32. Concatenate enough md5 blocks to cover len, then take the first len.
create or replace function helpers.random_string(len integer default 36)
    returns text
    volatile
    cost 1
    language sql
as
$$
select upper(substr(string_agg(md5(random()::text), ''), 1, len))
from generate_series(1, (len + 31) / 32);
$$;

select *
from stop_version_update('1.7', _component := 'common_helpers');
